# Generated by Django 5.2.3 on 2026-01-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True)),
                ('duration', models.IntegerField(help_text='Duration from parent to this node in minutes')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='routes.airportroute')),
            ],
            options={
                'unique_together': {('parent', 'side')},
            },
        ),
    ]
