# Generated by Django 5.2.3 on 2026-01-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportroute',
            old_name='side',
            new_name='position',
        ),
        migrations.AlterUniqueTogether(
            name='airportroute',
            unique_together={('parent', 'position')},
        ),
    ]
